bug fixes and partial v2 v3 sdk upgrade
sapcc/elektra pull request #1146
Opened 2022-11-11 10:57 UTC by sirajudheenam

2022-11-16 14:58 UTC, ArtieReus requested changes
Hi Sam! It looks much better now. Thx! See my comments.

2022-11-16 14:58 UTC, ArtieReus commented on Gemfile.lock
>        aws-sdk-ses
Do you still need the old version?

2022-11-16 14:58 UTC, ArtieReus commented on Gemfile.lock
> +    excon (0.93.1)
why are you downgrading excon?

2022-11-16 14:58 UTC, ArtieReus commented on Gemfile.lock
> +  revision: 1598d2a9d214d3e5fb9baa7cd3f56a42c79f4f06
Why did you change also the revision here?

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/controllers/email_service/domain_verifications_controller.rb
> +        Rails.logger.error  "\n ********* [controller - activate_dkim] - #{e.inspect} \n ***********\n"
Please format the error logs so the look the same as in the other plugins.

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/controllers/email_service/domain_verifications_controller.rb
> +        Rails.logger.error  "\n ********* [controller - activate_dkim] - #{e.inspect} \n ***********\n"
Same here

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/controllers/email_service/settings_controller.rb
>        @nebula_endpoint = "https://nebula.#{current_region}.cloud.sap"
Endpoints should be fetch from the catalog. See all other services.

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/controllers/email_service/web_controller.rb
> +    def test
Do you have a policy entry for this action?

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/javascript/email_service.coffee
> +replyTo = "fake3@gmail.com"
It would probably make sence here also to use a fake domain. We don't want to advertise gmail.

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/javascript/email_service.coffee
> +#     toRealAddresses = "fake1@gmail.com, fake2@gmail.com"
Same here.

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/javascript/email_service.coffee
>  #       simone@sbcglobal.net, tarreau@comcast.net,so much mal@verizon.net,
Do you still need to keep this?

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/javascript/email_service.coffee
>  #       $(emailSource).val sender
Why not use git to see the old code?

2022-11-16 14:58 UTC, ArtieReus commented on plugins/email_service/app/views/email_service/email_verifications/new.html.haml
> +      = f.input :identity, required: true, icon_hint: identity_hint, default: "fake1@gmail.com"
same here with the email

2022-11-21 10:50 UTC, sirajudheenam commented
Creating another PR. so closing this PR and deleting this branch.

2022-11-21 10:50 UTC, closed without merging