fix(wizard): check also for plugin_available to filter disabled plugins
sapcc/elektra pull request #1436
Opened 2024-10-16 12:49 UTC by hgw77

# Summary

* this will hopefully handle disabled plugins in the project wizard step

# Related Issues

#1402 

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings or errors.

2024-10-17 04:27 UTC, andypf commented
What do you mean with "hopefully"? Is it not possible to test this behavior?

2024-10-17 04:28 UTC, andypf requested changes
Please test this behavior. Is plugin_available? method available in controller?

2024-10-17 07:37 UTC, hgw77 commented
> Is plugin_available? method available in controller?

yes, otherwise it could not work

2024-10-17 18:09 UTC, andypf approved these changes

2024-10-18 15:59 UTC, edda approved these changes

2024-10-21 13:00 UTC, merged